---
- block:

  - name: 'empire : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/empire
      force: yes
      repo: https://github.com/EmpireProject/Empire.git

  - name: 'empire : run installer'
    command: /opt/empire/setup/install.sh
    args:
      chdir: /opt/empire
      creates: /opt/empire/data/empire-chain.pem
    environment:
      STAGING_KEY: RANDOM

  - name: 'empire : add startup script'
    template:
      dest: /usr/local/bin/empire
      mode: 0755
      src: ../templates/empire.sh

  tags:
    - exploitation
    - empire
