---
- block:

  - name: 'powersploit : clone repository (dev branch)'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /usr/share/powersploit
      force: yes
      repo: https://github.com/PowerShellMafia/PowerSploit.git
      version: dev

  tags:
    - exploitation
    - powersploit
