---
- block:

  - name: 'searchsploit : check for existing installation'
    stat: path=/opt/exploitdb
    register: exploitdb

  - name: 'searchsploit : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/exploitdb
      force: yes
      repo: https://github.com/offensive-security/exploitdb.git
    when: not exploitdb.stat.exists

  - name: 'searchsploit : create symlink'
    file:
      dest: /usr/local/bin/searchsploit
      src: /opt/exploitdb/searchsploit
      state: link

  tags:
    - exploitation
    - exploitdb
    - searchsploit
