---
- block:

  - name: 'linenum : create linux-binaries directory'
    file:
      path: /usr/share/linux-binaries
      state: directory

  - name: 'linenum : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /tmp/linenum
      force: yes
      repo: https://github.com/rebootuser/LinEnum.git

  - name: 'linenum : copy script'
    copy:
      dest: /usr/share/linux-binaries/LinEnum.sh
      mode: 0755
      remote_src: yes
      src: /tmp/linenum/LinEnum.sh

  - name: 'linenum : remove fragments'
    file:
      path: /tmp/linenum
      state: absent

  tags:
    - recon
    - linenum
