---
- block:

  - name: 'jtr : clone repository'
    git:
      accept_hostkey:  yes
      clone: yes
      depth: 1
      dest: /tmp/jtr
      force: yes
      repo: https://github.com/magnumripper/JohnTheRipper.git
      version: bleeding-jumbo

  - name: 'jtr : install requirements'
    apt:
      name:
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - yasm
        - libgmp-dev
        - libpcap-dev
        - pkg-config
        - libbz2-dev
      state: present
      update_cache: yes

  - name: 'jtr : configure'
    command: /tmp/jtr/src/configure
    args:
      chdir: /tmp/jtr/src

  - name: 'jtr : build'
    command: '{{ item }} chdir=/tmp/jtr/src'
    with_items:
      - './configure'
      - 'make -s clean'
      - 'make -sj4'

  - name: 'jtr : install tab completion'
    make:
      chdir: /tmp/jtr/src
      target: shell-completion

  - name: 'jtr : copy run directory'
    synchronize:
      dest: /opt/jtr
      src: /tmp/jtr/run/
    delegate_to: '{{ inventory_hostname }}'

  - name: 'jtr : add to path'
    lineinfile:
      line: 'export PATH=/opt/jtr:$PATH'
      path: /root/.zshrc
      regex: 'export PATH=\/opt\/jtr\:\$PATH'
      state: present

  - name: 'jtr : remove build fragments'
    file:
      path: /tmp/jtr
      state: absent

  tags:
    - cracking
    - jtr
