---
- include: cookie-monster.yml tags=web,cookie-monster
- include: dirb.yml tags=web,dirb
- include: eyewitness.yml tags=web,eyewitness
- include: gobuster.yml tags=web,gobuster
- include: magescan.yml tags=web,magescan
- include: nikto.yml tags=web,nikto
- include: shocker.yml tags=web,shocker
- include: sqlmap.yml tags=web,sqlmap
- include: wafw00f.yml tags=web,wafw00f
- include: wfuzz.yml tags=web,wfuzz
- include: whatweb.yml tags=web,whatweb
- include: wpscan.yml tags=web,wpscan
- include: wpxf.yml tags=web,wpxf
