---
- block:

  - name: 'packages : update apt cache'
    apt:
      update_cache: yes

  - name: 'packages : install common packages'
    apt:
      name:
        - awscli
        - build-essential
        - curl
        - git
        - gnupg2
        - libcurl4-openssl-dev
        - nano
        - nmap
        - openvpn
        - python
        - python-pip
        - python-setuptools
        - python3
        - python3-pip
        - python3-setuptools
        - smbclient
        - socat
        - software-properties-common
        - tar
        - ufw
        - unzip
        - vim
        - zip
        - zsh
      state: present

  - name: 'packages : install common Python modules'
    pip:
      name: pyopenssl
      state: present

  - name: 'packages : install virtualenv under Python 2'
    pip:
      executable: pip
      name: virtualenv
      state: present

  tags:
    - common
    - packages
