---
- block:
  - name: 'shell : install oh-my-zsh'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /root/.oh-my-zsh
      force: yes
      repo: https://github.com/robbyrussell/oh-my-zsh.git

  - name: 'shell : set permissions on oh-my-zsh directory'
    file:
      mode: 0755
      path: /root/.oh-my-zsh
      recurse: yes
      state: directory

  - name: 'shell : create .zshrc'
    copy:
      dest: /root/.zshrc
      remote_src: yes
      src: /root/.oh-my-zsh/templates/zshrc.zsh-template

  - name: 'shell : setup ZSH environment variable'
    lineinfile:
      path: /root/.zshrc
      regexp: export ZSH=
      line: export ZSH=/root/.oh-my-zsh

  - name: 'shell : setup bira theme'
    lineinfile:
      path: /root/.zshrc
      regexp: ZSH_THEME="robbyrussell"
      line: ZSH_THEME="bira"

  - name: 'shell : enable package suggestions'
    lineinfile:
      path: /root/.zshrc
      line: source /etc/zsh_command_not_found

  - name: 'shell : add explicit call to compinit to setup custom tab completions'
    lineinfile:
      path: /root/.zshrc
      line: compinit

  - name: 'shell : copy dircolors configuration'
    template:
      dest: /root/.dircolors
      mode: 0644
      src: ../templates/dircolors.conf

  - name: 'shell : add dircolors initialisation'
    lineinfile:
      path: /root/.zshrc
      line: 'eval "$(dircolors ~/.dircolors)"'

  - name: 'shell : add alias for python http server'
    lineinfile:
      path: /root/.zshrc
      line: 'alias serve-this="python -m SimpleHTTPServer"'

  - name: 'shell : add functions to parse dnsrecon and masscan output'
    lineinfile:
      path: /root/.zshrc
      line: '{{ item }}'
    with_items:
      - >
        function masscan_port_list {
          grep -oP "Ports: [0-9]+" "$1" | cut -d " " -f 2 | sort -u | tr "\n" "," | sed 's/,$//'
        }
      - >
        function masscan_ip_list {
          grep -oP "([0-9]{2,3}\.){3}[0-9]{2,3}" "$1" | sort -u
        }
      - >
        function extract_unique_domains_from_dnsrecon_json {
          grep -oP "([^\"]+?$2\")" "$1" | sed 's/"//' | sort -f -u
        }

  - name: 'shell : set default root shell'
    user:
      name: root
      shell: /bin/zsh
  tags:
    - common
    - shell
