---
- block:

  - name: 'apache : install packages'
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - php
        - php-xml
        - php-mbstring
        - php-curl
      state: present
      update_cache: yes

  - name: 'apache : stop and disable service'
    service:
      enabled: no
      name: apache2
      state: stopped

  tags:
    - services
    - apache
